# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 99cd38438f210ff23f63aebc70b22ed300ce574b53d3eff4cecea3c103d11cfde9ec562202f52491cd8415953a192bc48031ad22b93106f0a598273399e97cb5

test:
  secret_key_base: a12d23a5db36ab3be6e35c76045752c76e67967398a457eefc8989fd8c24e13d50061b4031b3af2e53d51d3f509d2ea118ada458c196495954dbe219b63033fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
